### ISSUE TITLE
ngFileSelect directive is not work

### ISSUE THREAD

**Issue by oowangoo** [danialfarid/angular-file-upload-bower#6]
tag:<input type="file" ng-file-select="method"/> 
when file is select no call method
the bug in "angular-file-upload-all.js" line 197 and 228.
please first 
   ' if ( ng-file-select ... )  attr.ngFileChange = attr.ngFileSelect;'
the second
   '	var changeFn = $parse(attr.ngFileChange);'

**Comment by danialfarid** [comment]
There is already an open issue for it, gonna be fixed in the next release
